package com.example.matchbook.ui.theme

import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)
val md_theme_light_primary = Color(0xFF006E0A)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF75FF68)
val md_theme_light_onPrimaryContainer = Color(0xFF002201)
val md_theme_light_secondary = Color(0xFF9E2A9B)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFD7F5)
val md_theme_light_onSecondaryContainer = Color(0xFF380038)
val md_theme_light_tertiary = Color(0xFF7B41B3)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFF0DBFF)
val md_theme_light_onTertiaryContainer = Color(0xFF2C0050)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFCFDF6)
val md_theme_light_onBackground = Color(0xFF1A1C19)
val md_theme_light_surface = Color(0xFFFCFDF6)
val md_theme_light_onSurface = Color(0xFF1A1C19)
val md_theme_light_surfaceVariant = Color(0xFFDFE4D8)
val md_theme_light_onSurfaceVariant = Color(0xFF42493F)
val md_theme_light_outline = Color(0xFF73796E)
val md_theme_light_inverseOnSurface = Color(0xFFF1F1EB)
val md_theme_light_inverseSurface = Color(0xFF2F312D)
val md_theme_light_inversePrimary = Color(0xFF4CE346)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF006E0A)
val md_theme_light_outlineVariant = Color(0xFFC2C8BC)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF4CE346)
val md_theme_dark_onPrimary = Color(0xFF003A03)
val md_theme_dark_primaryContainer = Color(0xFF005306)
val md_theme_dark_onPrimaryContainer = Color(0xFF75FF68)
val md_theme_dark_secondary = Color(0xFFFFAAF3)
val md_theme_dark_onSecondary = Color(0xFF5B005B)
val md_theme_dark_secondaryContainer = Color(0xFF810181)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFD7F5)
val md_theme_dark_tertiary = Color(0xFFDDB7FF)
val md_theme_dark_onTertiary = Color(0xFF4A0080)
val md_theme_dark_tertiaryContainer = Color(0xFF622599)
val md_theme_dark_onTertiaryContainer = Color(0xFFF0DBFF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1A1C19)
val md_theme_dark_onBackground = Color(0xFFE2E3DD)
val md_theme_dark_surface = Color(0xFF1A1C19)
val md_theme_dark_onSurface = Color(0xFFE2E3DD)
val md_theme_dark_surfaceVariant = Color(0xFF42493F)
val md_theme_dark_onSurfaceVariant = Color(0xFFC2C8BC)
val md_theme_dark_outline = Color(0xFF8C9387)
val md_theme_dark_inverseOnSurface = Color(0xFF1A1C19)
val md_theme_dark_inverseSurface = Color(0xFFE2E3DD)
val md_theme_dark_inversePrimary = Color(0xFF006E0A)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF4CE346)
val md_theme_dark_outlineVariant = Color(0xFF42493F)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF32CD32)